#!/bin/sh

set -x

(cd libgmshMessageStream; wclean)
(cd libgmshFoam; wclean)
(cd gmsh2ToFoam; wclean)
(cd foamToGmsh; wclean)
(cd foamMeshToGmsh; wclean)
(cd gmshFoamMonitor; wclean)
find . -name '*.stackdump' -exec rm \{\} \;
